on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Skip installing pacakge docs {makes the man-db trigger much faster) 
          # (I disabled `/doc` and `/info` too, just in case.)
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF
      - run: sudo apt install gcc-mingw-w64-x86-64 libz-mingw-w64-dev
      - uses: actions/checkout@v5
      - run: mkdir build-mingw32
      - run: ../configure --host="x86_64-pc-linux-gnu" --target="x86_64-w64-mingw32" CC="x86_64-w64-mingw32-gcc"
        working-directory: build-mingw32
      - run: make
        working-directory: build-mingw32
      - run: mkdir build
      - run: ../configure
        working-directory: build
      - run: make
        working-directory: build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: mkdir build
      - run: ../configure
        working-directory: build
      - run: make
        working-directory: build
 
